### ISSUE TITLE
Шаблон страницы изображения

### ISSUE THREAD

**Issue by irbees2008** [russsiq/gallery#1]
Привет , на странице изображения раньше было {{ image.src_thumb }}, сейчас нет, можешь вернуть

**Comment by russsiq** [comment]
Извини, офлайн был.

Смутно помню, но что-то выпиливал такое или подобное.

А какой смысл в миниатюре на странице полного изображения?

Давай посмотрю https://github.com/russsiq/gallery/blob/master/src/Gallery.php#L506

**Comment by russsiq** [comment]
Дай мне разбег в пару дней и я разберусь )

**Comment by irbees2008** [comment]
да заметил на днях только
